/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CourageLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface DeepInsights {
  'skillGapWarning' : string,
  'strengths' : Array<string>,
  'actionSteps' : Array<string>,
  'yearProjection' : string,
  'hiddenRisks' : Array<string>,
  'brutalTruth' : string,
}
export interface Question {
  'id' : bigint,
  'unlockCount' : bigint,
  'mode' : ScoreMode,
  'createdAt' : Time,
  'text' : string,
  'viewCount' : bigint,
  'isFeatured' : boolean,
  'scoreResult' : ScoreResult,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type ScoreMode = { 'money' : null } |
  { 'growth' : null } |
  { 'brutal' : null } |
  { 'emotion' : null } |
  { 'future' : null } |
  { 'logic' : null };
export interface ScoreResult {
  'score' : bigint,
  'insight' : string,
  'riskLevel' : RiskLevel,
  'courageLevel' : CourageLevel,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getDeepInsights' : ActorMethod<[bigint], DeepInsights>,
  'getFeaturedQuestionByMode' : ActorMethod<[ScoreMode], [] | [Question]>,
  'getScoreResult' : ActorMethod<[bigint], ScoreResult>,
  'getTopQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getTopQuestionsByUnlocks' : ActorMethod<[bigint], Array<Question>>,
  'setFeaturedQuestion' : ActorMethod<[bigint, ScoreMode], undefined>,
  'submitQuestion' : ActorMethod<[string, ScoreMode], bigint>,
  'unlockQuestion' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];