/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreMode = IDL.Variant({
  'money' : IDL.Null,
  'growth' : IDL.Null,
  'brutal' : IDL.Null,
  'emotion' : IDL.Null,
  'future' : IDL.Null,
  'logic' : IDL.Null,
});
export const Time = IDL.Int;
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const CourageLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ScoreResult = IDL.Record({
  'score' : IDL.Nat,
  'insight' : IDL.Text,
  'riskLevel' : RiskLevel,
  'courageLevel' : CourageLevel,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'unlockCount' : IDL.Nat,
  'mode' : ScoreMode,
  'createdAt' : Time,
  'text' : IDL.Text,
  'viewCount' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'scoreResult' : ScoreResult,
});
export const DeepInsights = IDL.Record({
  'skillGapWarning' : IDL.Text,
  'strengths' : IDL.Vec(IDL.Text),
  'actionSteps' : IDL.Vec(IDL.Text),
  'yearProjection' : IDL.Text,
  'hiddenRisks' : IDL.Vec(IDL.Text),
  'brutalTruth' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getDeepInsights' : IDL.Func([IDL.Nat], [DeepInsights], ['query']),
  'getFeaturedQuestionByMode' : IDL.Func(
      [ScoreMode],
      [IDL.Opt(Question)],
      ['query'],
    ),
  'getScoreResult' : IDL.Func([IDL.Nat], [ScoreResult], []),
  'getTopQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getTopQuestionsByUnlocks' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'setFeaturedQuestion' : IDL.Func([IDL.Nat, ScoreMode], [], []),
  'submitQuestion' : IDL.Func([IDL.Text, ScoreMode], [IDL.Nat], []),
  'unlockQuestion' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreMode = IDL.Variant({
    'money' : IDL.Null,
    'growth' : IDL.Null,
    'brutal' : IDL.Null,
    'emotion' : IDL.Null,
    'future' : IDL.Null,
    'logic' : IDL.Null,
  });
  const Time = IDL.Int;
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CourageLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ScoreResult = IDL.Record({
    'score' : IDL.Nat,
    'insight' : IDL.Text,
    'riskLevel' : RiskLevel,
    'courageLevel' : CourageLevel,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'unlockCount' : IDL.Nat,
    'mode' : ScoreMode,
    'createdAt' : Time,
    'text' : IDL.Text,
    'viewCount' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'scoreResult' : ScoreResult,
  });
  const DeepInsights = IDL.Record({
    'skillGapWarning' : IDL.Text,
    'strengths' : IDL.Vec(IDL.Text),
    'actionSteps' : IDL.Vec(IDL.Text),
    'yearProjection' : IDL.Text,
    'hiddenRisks' : IDL.Vec(IDL.Text),
    'brutalTruth' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getDeepInsights' : IDL.Func([IDL.Nat], [DeepInsights], ['query']),
    'getFeaturedQuestionByMode' : IDL.Func(
        [ScoreMode],
        [IDL.Opt(Question)],
        ['query'],
      ),
    'getScoreResult' : IDL.Func([IDL.Nat], [ScoreResult], []),
    'getTopQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getTopQuestionsByUnlocks' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'setFeaturedQuestion' : IDL.Func([IDL.Nat, ScoreMode], [], []),
    'submitQuestion' : IDL.Func([IDL.Text, ScoreMode], [IDL.Nat], []),
    'unlockQuestion' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };