/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface DeepInsights {
    skillGapWarning: string;
    strengths: Array<string>;
    actionSteps: Array<string>;
    yearProjection: string;
    hiddenRisks: Array<string>;
    brutalTruth: string;
}
export interface ScoreResult {
    score: bigint;
    insight: string;
    riskLevel: RiskLevel;
    courageLevel: CourageLevel;
}
export interface Question {
    id: bigint;
    unlockCount: bigint;
    mode: ScoreMode;
    createdAt: Time;
    text: string;
    viewCount: bigint;
    isFeatured: boolean;
    scoreResult: ScoreResult;
}
export enum CourageLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum ScoreMode {
    money = "money",
    growth = "growth",
    brutal = "brutal",
    emotion = "emotion",
    future = "future",
    logic = "logic"
}
export interface backendInterface {
    getAllQuestions(): Promise<Array<Question>>;
    getDeepInsights(questionId: bigint): Promise<DeepInsights>;
    getFeaturedQuestionByMode(mode: ScoreMode): Promise<Question | null>;
    getScoreResult(questionId: bigint): Promise<ScoreResult>;
    getTopQuestions(limit: bigint): Promise<Array<Question>>;
    getTopQuestionsByUnlocks(limit: bigint): Promise<Array<Question>>;
    setFeaturedQuestion(questionId: bigint, mode: ScoreMode): Promise<void>;
    submitQuestion(text: string, mode: ScoreMode): Promise<bigint>;
    unlockQuestion(questionId: bigint): Promise<void>;
}
import type { CourageLevel as _CourageLevel, Question as _Question, RiskLevel as _RiskLevel, ScoreMode as _ScoreMode, ScoreResult as _ScoreResult, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeepInsights(arg0: bigint): Promise<DeepInsights> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeepInsights(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeepInsights(arg0);
            return result;
        }
    }
    async getFeaturedQuestionByMode(arg0: ScoreMode): Promise<Question | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedQuestionByMode(to_candid_ScoreMode_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedQuestionByMode(to_candid_ScoreMode_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScoreResult(arg0: bigint): Promise<ScoreResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreResult(arg0);
                return from_candid_ScoreResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreResult(arg0);
            return from_candid_ScoreResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopQuestions(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopQuestions(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopQuestions(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopQuestionsByUnlocks(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopQuestionsByUnlocks(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopQuestionsByUnlocks(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setFeaturedQuestion(arg0: bigint, arg1: ScoreMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFeaturedQuestion(arg0, to_candid_ScoreMode_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFeaturedQuestion(arg0, to_candid_ScoreMode_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitQuestion(arg0: string, arg1: ScoreMode): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuestion(arg0, to_candid_ScoreMode_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuestion(arg0, to_candid_ScoreMode_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unlockQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockQuestion(arg0);
            return result;
        }
    }
}
function from_candid_CourageLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourageLevel): CourageLevel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ScoreMode_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScoreMode): ScoreMode {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ScoreResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScoreResult): ScoreResult {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Question]): Question | null {
    return value.length === 0 ? null : from_candid_Question_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    unlockCount: bigint;
    mode: _ScoreMode;
    createdAt: _Time;
    text: string;
    viewCount: bigint;
    isFeatured: boolean;
    scoreResult: _ScoreResult;
}): {
    id: bigint;
    unlockCount: bigint;
    mode: ScoreMode;
    createdAt: Time;
    text: string;
    viewCount: bigint;
    isFeatured: boolean;
    scoreResult: ScoreResult;
} {
    return {
        id: value.id,
        unlockCount: value.unlockCount,
        mode: from_candid_ScoreMode_n4(_uploadFile, _downloadFile, value.mode),
        createdAt: value.createdAt,
        text: value.text,
        viewCount: value.viewCount,
        isFeatured: value.isFeatured,
        scoreResult: from_candid_ScoreResult_n6(_uploadFile, _downloadFile, value.scoreResult)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: bigint;
    insight: string;
    riskLevel: _RiskLevel;
    courageLevel: _CourageLevel;
}): {
    score: bigint;
    insight: string;
    riskLevel: RiskLevel;
    courageLevel: CourageLevel;
} {
    return {
        score: value.score,
        insight: value.insight,
        riskLevel: from_candid_RiskLevel_n8(_uploadFile, _downloadFile, value.riskLevel),
        courageLevel: from_candid_CourageLevel_n10(_uploadFile, _downloadFile, value.courageLevel)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    money: null;
} | {
    growth: null;
} | {
    brutal: null;
} | {
    emotion: null;
} | {
    future: null;
} | {
    logic: null;
}): ScoreMode {
    return "money" in value ? ScoreMode.money : "growth" in value ? ScoreMode.growth : "brutal" in value ? ScoreMode.brutal : "emotion" in value ? ScoreMode.emotion : "future" in value ? ScoreMode.future : "logic" in value ? ScoreMode.logic : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): CourageLevel {
    return "low" in value ? CourageLevel.low : "high" in value ? CourageLevel.high : "medium" in value ? CourageLevel.medium : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ScoreMode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScoreMode): _ScoreMode {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScoreMode): {
    money: null;
} | {
    growth: null;
} | {
    brutal: null;
} | {
    emotion: null;
} | {
    future: null;
} | {
    logic: null;
} {
    return value == ScoreMode.money ? {
        money: null
    } : value == ScoreMode.growth ? {
        growth: null
    } : value == ScoreMode.brutal ? {
        brutal: null
    } : value == ScoreMode.emotion ? {
        emotion: null
    } : value == ScoreMode.future ? {
        future: null
    } : value == ScoreMode.logic ? {
        logic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
